version: 0.1

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 354230519776.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t <IMAGE_NAME> .
      - docker tag <IMAGE_NAME> <ECR_URL>
  post_build:
    commands:
      - docker push <ECR_URL>
      - printf '[{"name":"<TASK_DEFINITION_NAME>","imageUri":"%s"}]' <ECR_URL> > imagedefinitions.json

artifacts:
  files: imagedefinitions.json